// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHJZf7_TL722y8jGwZeRCxK9-DjpruFuQ',
    appId: '1:756334016242:web:725864fc145ae92800026b',
    messagingSenderId: '756334016242',
    projectId: 'ip-eps',
    authDomain: 'ip-eps.firebaseapp.com',
    storageBucket: 'ip-eps.firebasestorage.app',
    measurementId: 'G-JWWM07M99F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBivdadhNS8kOpTkPxLTPI8m1DlI1ZgQ2M',
    appId: '1:756334016242:android:f3a3d8db6aaa9bf000026b',
    messagingSenderId: '756334016242',
    projectId: 'ip-eps',
    storageBucket: 'ip-eps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqztgsTj3v_eTHokHI5l3P29oW0xDxDC8',
    appId: '1:756334016242:ios:f5fefb44047dfbeb00026b',
    messagingSenderId: '756334016242',
    projectId: 'ip-eps',
    storageBucket: 'ip-eps.firebasestorage.app',
    iosBundleId: 'com.example.ipEps',
  );
}
